name: Secret Scan on PR

on:
  pull_request:
    branches:
      - dev

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # full history needed by trufflehog

      - name: Install Python and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      - name: Run TruffleHog scan
        id: trufflehog
        run: |
          # Run trufflehog scan on the full repo
          trufflehog filesystem . --json > trufflehog-results.json || true

      - name: Check TruffleHog scan results
        run: |
          if grep -q '"stringsFound": \[' trufflehog-results.json; then
            echo "Secrets found! Failing the job."
            cat trufflehog-results.json
            exit 1
          else
            echo "No secrets found."
          fi
