name: Secret Scan with Trivy

# Trigger on PRs to main branch (adjust branches as needed)
on:
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    name: Trivy Secret Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout the PR source code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for thorough scanning

      # Install Trivy securely using official install script
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # Run Trivy secret scan with fail-on-severity set
      - name: Run Trivy Secret Scan
        run: |
          trivy secret --exit-code 1 --severity HIGH,CRITICAL --no-progress .

      # Success message if no secrets found
      - name: Scan Passed
        if: success()
        run: echo "✅ No secrets detected by Trivy. Ready to merge!"
