name: Secret Scan with Trivy

on:
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Secret Scan
        id: trivy-scan
        run: |
          trivy fs --security-checks secret --format json --output result.json .
          # Check if any secrets found by parsing the JSON result
          if grep -q '"Severity": "HIGH"' result.json || grep -q '"Severity": "CRITICAL"' result.json; then
            echo "Secrets found with HIGH or CRITICAL severity!"
            exit 1
          else
            echo "No high or critical secrets found."
          fi

      - name: Success message
        if: success()
        run: echo "✅ No secrets detected by Trivy."
