name: Secret Scan on PR

on:
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget jq
          wget https://github.com/aquasecurity/trivy/releases/download/v0.44.1/trivy_0.44.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.44.1_Linux-64bit.deb

      - name: Run Trivy Secret Scan
        id: trivy-scan
        run: |
          # Run trivy and output JSON
          trivy fs --scanners secret --exit-code 1 --format json . > trivy-results.json

          # Check if any secrets were found by counting entries with secrets array non-empty
          FOUND=$(jq '[.Results[]? | select(.Secrets != null and (.Secrets | length) > 0)] | length' trivy-results.json)

          echo "Found secrets count: $FOUND"

          if [ "$FOUND" -gt 0 ]; then
            echo "Secrets detected! Please fix before merging."
            exit 1
          else
            echo "No secrets found."
          fi
