name: Secret Scan

on:
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run Trivy secret scan
        run: |
          trivy fs --scanners secret --format json --output trivy_report.json .

      - name: Show Trivy report
        run: cat trivy_report.json

      - name: Fail if secrets found
        run: |
          secrets_found=$(jq '[.Results[]?.Secrets // [] | length] | add // 0' trivy_report.json)
          echo "Secrets found: $secrets_found"
          if [ "$secrets_found" -gt 0 ]; then
            echo "Secrets detected! Failing the workflow."
            exit 1
          else
            echo "No secrets found."
          fi
