name: Secret Scan with Trivy

on:
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Secret Scan
        id: trivy_scan
        run: |
          trivy fs --security-checks secret --format json --output result.json .
          echo "Scan results:"
          cat result.json
          # Check if HIGH or CRITICAL severity findings exist
          if jq -e '.Results[].Secrets[] | select(.Severity == "HIGH" or .Severity == "CRITICAL")' result.json > /dev/null; then
            echo "❌ Secrets with HIGH or CRITICAL severity found!"
            exit 1
          else
            echo "✅ No high or critical severity secrets found."
          fi

      - name: Success message
        if: success()
        run: echo "All clear! No secrets detected by Trivy."
